// Autogenerated from Pigeon (v3.2.9), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, ScanStep) {
  ScanStepBlinkId = 0,
  ScanStepDocumentVerification = 1,
};

typedef NS_ENUM(NSUInteger, Liveness) {
  LivenessFacetec = 0,
  LivenessIProov = 1,
};

typedef NS_ENUM(NSUInteger, LivenessUIFilter) {
  LivenessUIFilterClassic = 0,
  LivenessUIFilterShaded = 1,
  LivenessUIFilterVibrant = 2,
};

typedef NS_ENUM(NSUInteger, ResultFieldType) {
  ResultFieldTypeStringResult = 0,
  ResultFieldTypeInsertedStringResult = 1,
  ResultFieldTypeEditedStringResult = 2,
  ResultFieldTypeDateResult = 3,
  ResultFieldTypeBooleanResult = 4,
};

typedef NS_ENUM(NSUInteger, FieldType) {
  FieldTypeFIRST_NAME = 0,
  FieldTypeLAST_NAME = 1,
  FieldTypeFULL_NAME = 2,
  FieldTypeLOCALIZED_NAME = 3,
  FieldTypeADDITIONAL_NAME_INFORMATION = 4,
  FieldTypeDATE_OF_BIRTH = 5,
  FieldTypePLACE_OF_BIRTH = 6,
  FieldTypeDATE_OF_ISSUE = 7,
  FieldTypeDATE_OF_EXPIRY = 8,
  FieldTypeDATE_OF_EXPIRY_PERMANENT = 9,
  FieldTypeDOCUMENT_NUMBER = 10,
  FieldTypePERSONAL_ID_NUMBER = 11,
  FieldTypeDOCUMENT_ADDITIONAL_NUMBER = 12,
  FieldTypeADDRESS = 13,
  FieldTypeRESIDENTIAL_STATUS = 14,
  FieldTypeADDITIONAL_ADDRESS_INFORMATION = 15,
  FieldTypeNATIONALITY = 16,
  FieldTypeISSUING_AUTHORITY = 17,
  FieldTypeSEX = 18,
  FieldTypeMARITAL_STATUS = 19,
  FieldTypeRACE = 20,
  FieldTypeRELIGION = 21,
  FieldTypePROFESSION = 22,
  FieldTypeEMPLOYER = 23,
};

typedef NS_ENUM(NSUInteger, VerificationType) {
  VerificationTypeSUCCESS = 0,
  VerificationTypeFAILED = 1,
  VerificationTypeCANCELLED = 2,
  VerificationTypeNEEDS_REVIEW = 3,
};

typedef NS_ENUM(NSUInteger, BarStyle) {
  BarStyleWhite = 0,
  BarStyleBlack = 1,
};

typedef NS_ENUM(NSUInteger, KeyboardType) {
  KeyboardTypeDEFAULT = 0,
  KeyboardTypeASCII_CAPABLE = 1,
  KeyboardTypeNUMBERS_AND_PUNCTUATIONS = 2,
  KeyboardTypeURL = 3,
  KeyboardTypeNUMBER_PAD = 4,
  KeyboardTypePHONE_PAD = 5,
  KeyboardTypeNAME_PHONE_PAD = 6,
  KeyboardTypeEMAIL = 7,
  KeyboardTypeDECIMAL_PAD = 8,
  KeyboardTypeTWITTER = 9,
  KeyboardTypeWEB_SEARCH = 10,
  KeyboardTypeASCII_CAPABLE_NUMPAD = 11,
};

typedef NS_ENUM(NSUInteger, DocumentImageColorStatus) {
  DocumentImageColorStatusNotAvailable = 0,
  DocumentImageColorStatusBlackAndWhite = 1,
  DocumentImageColorStatusColor = 2,
};

typedef NS_ENUM(NSUInteger, ImageAnalysisDetectionStatus) {
  ImageAnalysisDetectionStatusNotAvailable = 0,
  ImageAnalysisDetectionStatusNotDetected = 1,
  ImageAnalysisDetectionStatusDetected = 2,
};

typedef NS_ENUM(NSUInteger, Country) {
  CountryNone = 0,
  CountryAlbania = 1,
  CountryAlgeria = 2,
  CountryArgentina = 3,
  CountryAustralia = 4,
  CountryAustria = 5,
  CountryAzerbaijan = 6,
  CountryBahrain = 7,
  CountryBangladesh = 8,
  CountryBelgium = 9,
  CountryBosniaAndHerzegovina = 10,
  CountryBrunei = 11,
  CountryBulgaria = 12,
  CountryCambodia = 13,
  CountryCanada = 14,
  CountryChile = 15,
  CountryColombia = 16,
  CountryCostaRica = 17,
  CountryCroatia = 18,
  CountryCyprus = 19,
  CountryCzechia = 20,
  CountryDenmark = 21,
  CountryDominicanRepublic = 22,
  CountryEgypt = 23,
  CountryEstonia = 24,
  CountryFinland = 25,
  CountryFrance = 26,
  CountryGeorgia = 27,
  CountryGermany = 28,
  CountryGhana = 29,
  CountryGreece = 30,
  CountryGuatemala = 31,
  CountryHongKong = 32,
  CountryHungary = 33,
  CountryIndia = 34,
  CountryIndonesia = 35,
  CountryIreland = 36,
  CountryIsrael = 37,
  CountryItaly = 38,
  CountryJordan = 39,
  CountryKazakhstan = 40,
  CountryKenya = 41,
  CountryKosovo = 42,
  CountryKuwait = 43,
  CountryLatvia = 44,
  CountryLithuania = 45,
  CountryMalaysia = 46,
  CountryMaldives = 47,
  CountryMalta = 48,
  CountryMauritius = 49,
  CountryMexico = 50,
  CountryMorocco = 51,
  CountryNetherlands = 52,
  CountryNewZealand = 53,
  CountryNigeria = 54,
  CountryPakistan = 55,
  CountryPanama = 56,
  CountryParaguay = 57,
  CountryPhilippines = 58,
  CountryPoland = 59,
  CountryPortugal = 60,
  CountryPuertoRico = 61,
  CountryQatar = 62,
  CountryRomania = 63,
  CountryRussia = 64,
  CountrySaudiArabia = 65,
  CountrySerbia = 66,
  CountrySingapore = 67,
  CountrySlovakia = 68,
  CountrySlovenia = 69,
  CountrySouthAfrica = 70,
  CountrySpain = 71,
  CountrySweden = 72,
  CountrySwitzerland = 73,
  CountryTaiwan = 74,
  CountryThailand = 75,
  CountryTunisia = 76,
  CountryTurkey = 77,
  CountryUAE = 78,
  CountryUganda = 79,
  CountryUK = 80,
  CountryUkraine = 81,
  CountryUsa = 82,
  CountryVietnam = 83,
  CountryBrazil = 84,
  CountryNorway = 85,
  CountryOman = 86,
  CountryEcuador = 87,
  CountryElSalvador = 88,
  CountrySriLanka = 89,
  CountryPeru = 90,
  CountryUruguay = 91,
  CountryBahamas = 92,
  CountryBermuda = 93,
  CountryBolivia = 94,
  CountryChina = 95,
  CountryEuropeanUnion = 96,
  CountryHaiti = 97,
  CountryHonduras = 98,
  CountryIceland = 99,
  CountryJapan = 100,
  CountryLuxembourg = 101,
  CountryMontenegro = 102,
  CountryNicaragua = 103,
  CountrySouthKorea = 104,
  CountryVenezuela = 105,
  CountryAfghanistan = 106,
  CountryAlandIslands = 107,
  CountryAmericanSamoa = 108,
  CountryAndorra = 109,
  CountryAngola = 110,
  CountryAnguilla = 111,
  CountryAntarctica = 112,
  CountryAntiguaAndBarbuda = 113,
  CountryArmenia = 114,
  CountryAruba = 115,
  CountryBailiwickOfGuernsey = 116,
  CountryBailiwickOfJersey = 117,
  CountryBarbados = 118,
  CountryBelarus = 119,
  CountryBelize = 120,
  CountryBenin = 121,
  CountryBhutan = 122,
  CountryBonaireSaintEustatiusAndSaba = 123,
  CountryBotswana = 124,
  CountryBouvetIsland = 125,
  CountryBritishIndianOceanTerritory = 126,
  CountryBurkinaFaso = 127,
  CountryBurundi = 128,
  CountryCameroon = 129,
  CountryCapeVerde = 130,
  CountryCaribbeanNetherlands = 131,
  CountryCaymanIslands = 132,
  CountryCentralAfricanRepublic = 133,
  CountryChad = 134,
  CountryChristmasIsland = 135,
  CountryCocosIslands = 136,
  CountryComoros = 137,
  CountryCongo = 138,
  CountryCookIslands = 139,
  CountryCuba = 140,
  CountryCuracao = 141,
  CountryDemocraticRepublicOfTheCongo = 142,
  CountryDjibouti = 143,
  CountryDominica = 144,
  CountryEastTimor = 145,
  CountryEquatorialGuinea = 146,
  CountryEritrea = 147,
  CountryEthiopia = 148,
  CountryFalklandIslands = 149,
  CountryFaroeIslands = 150,
  CountryFederatedStatesOfMicronesia = 151,
  CountryFiji = 152,
  CountryFrenchGuiana = 153,
  CountryFrenchPolynesia = 154,
  CountryFrenchSouthernTerritories = 155,
  CountryGabon = 156,
  CountryGambia = 157,
  CountryGibraltar = 158,
  CountryGreenland = 159,
  CountryGrenada = 160,
  CountryGuadeloupe = 161,
  CountryGuam = 162,
  CountryGuinea = 163,
  CountryGuineaBissau = 164,
  CountryGuyana = 165,
  CountryHeardIslandAndMcdonaldIslands = 166,
  CountryIran = 167,
  CountryIraq = 168,
  CountryIsleOfMan = 169,
  CountryIvoryCoast = 170,
  CountryJamaica = 171,
  CountryKiribati = 172,
  CountryKyrgyzstan = 173,
  CountryLaos = 174,
  CountryLebanon = 175,
  CountryLesotho = 176,
  CountryLiberia = 177,
  CountryLibya = 178,
  CountryLiechtenstein = 179,
  CountryMacau = 180,
  CountryMadagascar = 181,
  CountryMalawi = 182,
  CountryMali = 183,
  CountryMarshallIslands = 184,
  CountryMartinique = 185,
  CountryMauritania = 186,
  CountryMayotte = 187,
  CountryMoldova = 188,
  CountryMonaco = 189,
  CountryMongolia = 190,
  CountryMontserrat = 191,
  CountryMozambique = 192,
  CountryMyanmar = 193,
  CountryNamibia = 194,
  CountryNauru = 195,
  CountryNepal = 196,
  CountryNewCaledonia = 197,
  CountryNiger = 198,
  CountryNiue = 199,
  CountryNorfolkIsland = 200,
  CountryNorthernCyprus = 201,
  CountryNorthernMarianaIslands = 202,
  CountryNorthKorea = 203,
  CountryNorthMacedonia = 204,
  CountryPalau = 205,
  CountryPalestine = 206,
  CountryPapuaNewGuinea = 207,
  CountryPitcairn = 208,
  CountryReunion = 209,
  CountryRwanda = 210,
  CountrySaintBarthelemy = 211,
  CountrySaintHelenaAscensionAndTristianDaCunha = 212,
  CountrySaintKittsAndNevis = 213,
  CountrySaintLucia = 214,
  CountrySaintMartin = 215,
  CountrySaintPierreAndMiquelon = 216,
  CountrySaintVincentAndTheGrenadines = 217,
  CountrySamoa = 218,
  CountrySanMarino = 219,
  CountrySaoTomeAndPrincipe = 220,
  CountrySenegal = 221,
  CountrySeychelles = 222,
  CountrySierraLeone = 223,
  CountrySintMaarten = 224,
  CountrySolomonIslands = 225,
  CountrySomalia = 226,
  CountrySouthGeorgiaAndTheSouthSandwichIslands = 227,
  CountrySouthSudan = 228,
  CountrySudan = 229,
  CountrySuriname = 230,
  CountrySvalbardAndJanMayen = 231,
  CountryEswatini = 232,
  CountrySyria = 233,
  CountryTajikistan = 234,
  CountryTanzania = 235,
  CountryTogo = 236,
  CountryTokelau = 237,
  CountryTonga = 238,
  CountryTrinidadAndTobago = 239,
  CountryTurkmenistan = 240,
  CountryTurksAndCaicosIslands = 241,
  CountryTuvalu = 242,
  CountryUnitedStatesMinorOutlyingIslands = 243,
  CountryUzbekistan = 244,
  CountryVanuatu = 245,
  CountryVaticanCity = 246,
  CountryVirginIslandsBritish = 247,
  CountryVirginIslandsUs = 248,
  CountryWallisAndFutuna = 249,
  CountryWesternSahara = 250,
  CountryYemen = 251,
  CountryYugoslavia = 252,
  CountryZambia = 253,
  CountryZimbabwe = 254,
};

typedef NS_ENUM(NSUInteger, Region) {
  RegionNone = 0,
  RegionAlabama = 1,
  RegionAlaska = 2,
  RegionAlberta = 3,
  RegionArizona = 4,
  RegionArkansas = 5,
  RegionAustralianCapitalTerritory = 6,
  RegionBritishColumbia = 7,
  RegionCalifornia = 8,
  RegionColorado = 9,
  RegionConnecticut = 10,
  RegionDelaware = 11,
  RegionDistrictOfColumbia = 12,
  RegionFlorida = 13,
  RegionGeorgia = 14,
  RegionHawaii = 15,
  RegionIdaho = 16,
  RegionIllinois = 17,
  RegionIndiana = 18,
  RegionIowa = 19,
  RegionKansas = 20,
  RegionKentucky = 21,
  RegionLouisiana = 22,
  RegionMaine = 23,
  RegionManitoba = 24,
  RegionMaryland = 25,
  RegionMassachusetts = 26,
  RegionMichigan = 27,
  RegionMinnesota = 28,
  RegionMississippi = 29,
  RegionMissouri = 30,
  RegionMontana = 31,
  RegionNebraska = 32,
  RegionNevada = 33,
  RegionNewBrunswick = 34,
  RegionNewHampshire = 35,
  RegionNewJersey = 36,
  RegionNewMexico = 37,
  RegionNewSouthWales = 38,
  RegionNewYork = 39,
  RegionNorthernTerritory = 40,
  RegionNorthCarolina = 41,
  RegionNorthDakota = 42,
  RegionNovaScotia = 43,
  RegionOhio = 44,
  RegionOklahoma = 45,
  RegionOntario = 46,
  RegionOregon = 47,
  RegionPennsylvania = 48,
  RegionQuebec = 49,
  RegionQueensland = 50,
  RegionRhodeIsland = 51,
  RegionSaskatchewan = 52,
  RegionSouthAustralia = 53,
  RegionSouthCarolina = 54,
  RegionSouthDakota = 55,
  RegionTasmania = 56,
  RegionTennessee = 57,
  RegionTexas = 58,
  RegionUtah = 59,
  RegionVermont = 60,
  RegionVictoria = 61,
  RegionVirginia = 62,
  RegionWashington = 63,
  RegionWesternAustralia = 64,
  RegionWestVirginia = 65,
  RegionWisconsin = 66,
  RegionWyoming = 67,
  RegionYukon = 68,
  RegionCiudadDeMexico = 69,
  RegionJalisco = 70,
  RegionNewfoundlandAndLabrador = 71,
  RegionNuevoLeon = 72,
  RegionBajaCalifornia = 73,
  RegionChihuahua = 74,
  RegionGuanajuato = 75,
  RegionGuerrero = 76,
  RegionMexico = 77,
  RegionMichoacan = 78,
  RegionNewYorkCity = 79,
  RegionTamaulipas = 80,
  RegionVeracruz = 81,
  RegionChiapas = 82,
  RegionCoahuila = 83,
  RegionDurango = 84,
  RegionGuerreroCocula = 85,
  RegionGuerreroJuchitan = 86,
  RegionGuerreroTepecoacuilco = 87,
  RegionGuerreroTlacoapa = 88,
  RegionGujarat = 89,
  RegionHidalgo = 90,
  RegionKarnataka = 91,
  RegionKerala = 92,
  RegionKhyberPakhtunkhwa = 93,
  RegionMadhyaPradesh = 94,
  RegionMaharashtra = 95,
  RegionMorelos = 96,
  RegionNayarit = 97,
  RegionOaxaca = 98,
  RegionPuebla = 99,
  RegionPunjab = 100,
  RegionQueretaro = 101,
  RegionSanLuisPotosi = 102,
  RegionSinaloa = 103,
  RegionSonora = 104,
  RegionTabasco = 105,
  RegionTamilNadu = 106,
  RegionYucatan = 107,
  RegionZacatecas = 108,
  RegionAguascalientes = 109,
  RegionBajaCaliforniaSur = 110,
  RegionCampeche = 111,
  RegionColima = 112,
  RegionQuintanaRooBenitoJuarez = 113,
};

typedef NS_ENUM(NSUInteger, Type) {
  TypeNone = 0,
  TypeConsularId = 1,
  TypeDl = 2,
  TypeDlPublicServicesCard = 3,
  TypeEmploymentPass = 4,
  TypeFinCard = 5,
  TypeId = 6,
  TypeMultipurposeId = 7,
  TypeMyKad = 8,
  TypeMyKid = 9,
  TypeMyPR = 10,
  TypeMyTentera = 11,
  TypePanCard = 12,
  TypeProfessionalId = 13,
  TypePublicServicesCard = 14,
  TypeResidencePermit = 15,
  TypeResidentId = 16,
  TypeTemporaryResidencePermit = 17,
  TypeVoterId = 18,
  TypeWorkPermit = 19,
  TypeIKad = 20,
  TypeMilitaryId = 21,
  TypeMyKas = 22,
  TypeSocialSecurityCard = 23,
  TypeHealthInsuranceCard = 24,
  TypePassport = 25,
  TypeSPass = 26,
  TypeAddressCard = 27,
  TypeAlienId = 28,
  TypeAlienPassport = 29,
  TypeGreenCard = 30,
  TypeMinorsId = 31,
  TypePostalId = 32,
  TypeProfessionalDl = 33,
  TypeTaxId = 34,
  TypeWeaponPermit = 35,
  TypeVisa = 36,
  TypeBorderCrossingCard = 37,
  TypeDriverCard = 38,
  TypeGlobalEntryCard = 39,
  TypeMypolis = 40,
  TypeNexusCard = 41,
  TypePassportCard = 42,
  TypeProofOfAgeCard = 43,
  TypeRefugeeId = 44,
  TypeTribalId = 45,
  TypeVeteranId = 46,
  TypeCitizenshipCertificate = 47,
};

typedef NS_ENUM(NSUInteger, ConditionName) {
  ConditionNameStarts_With = 0,
  ConditionNameIs_Digit = 1,
  ConditionNameMin_Length = 2,
  ConditionNameRequired = 3,
  ConditionNameEqual_To = 4,
  ConditionNameNot_Equal_To = 5,
};

typedef NS_ENUM(NSUInteger, FilterName) {
  FilterNameEqual_To = 0,
  FilterNameNot_Equal_To = 1,
  FilterNameIs_In = 2,
  FilterNameNot_In = 3,
};

@class VerificationResult;
@class FieldValidator;
@class DocumentFilter;
@class ModificationConfig;
@class DocumentField;
@class VerificationServiceSettings;
@class LivenessStep;
@class LivenessStepOptions;
@class RequestTimeout;
@class DocumentScanStep;
@class IdvConfiguration;
@class SimpleDate;
@class ResultField;
@class ClassInfo;
@class ImageAnalysisResult;
@class DocumentResult;
@class IdvColor;
@class IdvFont;
@class IdvFontFamily;
@class IdvLocalizationTheme;
@class IdvColorTheme;
@class IdvFontTheme;
@class IdvImageTheme;
@class IdvSize;
@class IdvViewTheme;
@class IdvNavigationTheme;
@class IdvDateFormatterTheme;

@interface VerificationResult : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithVerificationType:(VerificationType)verificationType;
@property(nonatomic, assign) VerificationType verificationType;
@end

@interface FieldValidator : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithConditionName:(ConditionName)conditionName
    stringValue:(nullable NSString *)stringValue
    intValue:(nullable NSNumber *)intValue
    ignoreCase:(nullable NSNumber *)ignoreCase;
@property(nonatomic, assign) ConditionName conditionName;
@property(nonatomic, copy, nullable) NSString * stringValue;
@property(nonatomic, strong, nullable) NSNumber * intValue;
@property(nonatomic, strong, nullable) NSNumber * ignoreCase;
@end

@interface DocumentFilter : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCountries:(nullable NSArray<NSNumber *> *)countries
    regions:(nullable NSArray<NSNumber *> *)regions
    types:(nullable NSArray<NSNumber *> *)types
    allowScanning:(NSNumber *)allowScanning;
@property(nonatomic, strong, nullable) NSArray<NSNumber *> * countries;
@property(nonatomic, strong, nullable) NSArray<NSNumber *> * regions;
@property(nonatomic, strong, nullable) NSArray<NSNumber *> * types;
@property(nonatomic, strong) NSNumber * allowScanning;
@end

@interface ModificationConfig : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithEditable:(NSNumber *)editable
    insertable:(NSNumber *)insertable
    validators:(nullable NSArray<FieldValidator *> *)validators
    keyboardType:(KeyboardType)keyboardType;
@property(nonatomic, strong) NSNumber * editable;
@property(nonatomic, strong) NSNumber * insertable;
@property(nonatomic, strong, nullable) NSArray<FieldValidator *> * validators;
@property(nonatomic, assign) KeyboardType keyboardType;
@end

@interface DocumentField : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithType:(FieldType)type
    modificationConfig:(nullable ModificationConfig *)modificationConfig;
@property(nonatomic, assign) FieldType type;
@property(nonatomic, strong, nullable) ModificationConfig * modificationConfig;
@end

@interface VerificationServiceSettings : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithUrl:(NSString *)url
    requestTimeout:(nullable RequestTimeout *)requestTimeout
    headers:(nullable NSDictionary<NSString *, NSString *> *)headers
    publicKeyPins:(nullable NSArray<NSString *> *)publicKeyPins
    isUsingSelfSignedCertificate:(nullable NSNumber *)isUsingSelfSignedCertificate;
@property(nonatomic, copy) NSString * url;
@property(nonatomic, strong, nullable) RequestTimeout * requestTimeout;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * headers;
@property(nonatomic, strong, nullable) NSArray<NSString *> * publicKeyPins;
@property(nonatomic, strong, nullable) NSNumber * isUsingSelfSignedCertificate;
@end

@interface LivenessStep : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithInitializeInProduction:(nullable NSNumber *)initializeInProduction
    liveness:(Liveness)liveness
    options:(nullable LivenessStepOptions *)options;
@property(nonatomic, strong, nullable) NSNumber * initializeInProduction;
@property(nonatomic, assign) Liveness liveness;
@property(nonatomic, strong, nullable) LivenessStepOptions * options;
@end

@interface LivenessStepOptions : NSObject
+ (instancetype)makeWithFilter:(LivenessUIFilter)filter;
@property(nonatomic, assign) LivenessUIFilter filter;
@end

@interface RequestTimeout : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithConnectionTimeout:(NSNumber *)connectionTimeout
    writeTimeout:(NSNumber *)writeTimeout
    readTimeout:(NSNumber *)readTimeout
    timeoutIntervalForRequest:(NSNumber *)timeoutIntervalForRequest
    timeoutIntervalForResource:(NSNumber *)timeoutIntervalForResource;
@property(nonatomic, strong) NSNumber * connectionTimeout;
@property(nonatomic, strong) NSNumber * writeTimeout;
@property(nonatomic, strong) NSNumber * readTimeout;
@property(nonatomic, strong) NSNumber * timeoutIntervalForRequest;
@property(nonatomic, strong) NSNumber * timeoutIntervalForResource;
@end

@interface DocumentScanStep : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithScanStep:(ScanStep)scanStep
    androidLicenseFileName:(nullable NSString *)androidLicenseFileName
    iOSLicense:(nullable NSString *)iOSLicense
    showDocumentImages:(nullable NSNumber *)showDocumentImages
    documentFields:(nullable NSArray<DocumentField *> *)documentFields
    hiddenDocumentFields:(nullable NSArray<DocumentField *> *)hiddenDocumentFields
    attachDocumentListener:(nullable NSNumber *)attachDocumentListener
    documentFilter:(nullable DocumentFilter *)documentFilter
    skipUnsupportedBack:(nullable NSNumber *)skipUnsupportedBack
    showResultHeader:(nullable NSNumber *)showResultHeader;
@property(nonatomic, assign) ScanStep scanStep;
@property(nonatomic, copy, nullable) NSString * androidLicenseFileName;
@property(nonatomic, copy, nullable) NSString * iOSLicense;
@property(nonatomic, strong, nullable) NSNumber * showDocumentImages;
@property(nonatomic, strong, nullable) NSArray<DocumentField *> * documentFields;
@property(nonatomic, strong, nullable) NSArray<DocumentField *> * hiddenDocumentFields;
@property(nonatomic, strong, nullable) NSNumber * attachDocumentListener;
@property(nonatomic, strong, nullable) DocumentFilter * documentFilter;
@property(nonatomic, strong, nullable) NSNumber * skipUnsupportedBack;
@property(nonatomic, strong, nullable) NSNumber * showResultHeader;
@end

@interface IdvConfiguration : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithScanStep:(DocumentScanStep *)scanStep
    livenessStep:(LivenessStep *)livenessStep
    verificationServiceSettings:(VerificationServiceSettings *)verificationServiceSettings
    dateFormat:(nullable NSString *)dateFormat
    disableScreenshots:(nullable NSNumber *)disableScreenshots;
@property(nonatomic, strong) DocumentScanStep * scanStep;
@property(nonatomic, strong) LivenessStep * livenessStep;
@property(nonatomic, strong) VerificationServiceSettings * verificationServiceSettings;
@property(nonatomic, copy, nullable) NSString * dateFormat;
@property(nonatomic, strong, nullable) NSNumber * disableScreenshots;
@end

@interface SimpleDate : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithYear:(NSNumber *)year
    month:(NSNumber *)month
    day:(NSNumber *)day;
@property(nonatomic, strong) NSNumber * year;
@property(nonatomic, strong) NSNumber * month;
@property(nonatomic, strong) NSNumber * day;
@end

@interface ResultField : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithType:(FieldType)type
    resultFieldType:(ResultFieldType)resultFieldType
    value1:(nullable NSString *)value1
    value2:(nullable NSString *)value2
    boolValue:(nullable NSNumber *)boolValue
    simpleDate:(nullable SimpleDate *)simpleDate
    insertable:(nullable NSNumber *)insertable
    editable:(nullable NSNumber *)editable
    keyboardType:(KeyboardType)keyboardType
    originalValue:(nullable NSString *)originalValue
    insertedValue:(nullable NSString *)insertedValue
    editedValue:(nullable NSString *)editedValue
    key:(nullable NSString *)key
    value:(nullable NSString *)value;
@property(nonatomic, assign) FieldType type;
@property(nonatomic, assign) ResultFieldType resultFieldType;
@property(nonatomic, copy, nullable) NSString * value1;
@property(nonatomic, copy, nullable) NSString * value2;
@property(nonatomic, strong, nullable) NSNumber * boolValue;
@property(nonatomic, strong, nullable) SimpleDate * simpleDate;
@property(nonatomic, strong, nullable) NSNumber * insertable;
@property(nonatomic, strong, nullable) NSNumber * editable;
@property(nonatomic, assign) KeyboardType keyboardType;
@property(nonatomic, copy, nullable) NSString * originalValue;
@property(nonatomic, copy, nullable) NSString * insertedValue;
@property(nonatomic, copy, nullable) NSString * editedValue;
@property(nonatomic, copy, nullable) NSString * key;
@property(nonatomic, copy, nullable) NSString * value;
@end

@interface ClassInfo : NSObject
+ (instancetype)makeWithCountry:(Country)country
    region:(Region)region
    type:(Type)type
    empty:(nullable NSNumber *)empty
    countryName:(nullable NSString *)countryName
    isoNumericCountryCode:(nullable NSString *)isoNumericCountryCode
    isoAlpha2CountryCode:(nullable NSString *)isoAlpha2CountryCode
    isoAlpha3CountryCode:(nullable NSString *)isoAlpha3CountryCode;
@property(nonatomic, assign) Country country;
@property(nonatomic, assign) Region region;
@property(nonatomic, assign) Type type;
@property(nonatomic, strong, nullable) NSNumber * empty;
@property(nonatomic, copy, nullable) NSString * countryName;
@property(nonatomic, copy, nullable) NSString * isoNumericCountryCode;
@property(nonatomic, copy, nullable) NSString * isoAlpha2CountryCode;
@property(nonatomic, copy, nullable) NSString * isoAlpha3CountryCode;
@end

@interface ImageAnalysisResult : NSObject
+ (instancetype)makeWithIsBlurred:(nullable NSNumber *)isBlurred
    documentImageColorStatus:(DocumentImageColorStatus)documentImageColorStatus
    documentImageMoireStatus:(ImageAnalysisDetectionStatus)documentImageMoireStatus
    faceDetectionStatus:(ImageAnalysisDetectionStatus)faceDetectionStatus
    mrzDetectionStatus:(ImageAnalysisDetectionStatus)mrzDetectionStatus
    barcodeDetectionStatus:(ImageAnalysisDetectionStatus)barcodeDetectionStatus;
@property(nonatomic, strong, nullable) NSNumber * isBlurred;
@property(nonatomic, assign) DocumentImageColorStatus documentImageColorStatus;
@property(nonatomic, assign) ImageAnalysisDetectionStatus documentImageMoireStatus;
@property(nonatomic, assign) ImageAnalysisDetectionStatus faceDetectionStatus;
@property(nonatomic, assign) ImageAnalysisDetectionStatus mrzDetectionStatus;
@property(nonatomic, assign) ImageAnalysisDetectionStatus barcodeDetectionStatus;
@end

@interface DocumentResult : NSObject
+ (instancetype)makeWithResultsFields:(nullable NSArray<ResultField *> *)resultsFields
    faceImage:(nullable FlutterStandardTypedData *)faceImage
    frontSideDocumentImage:(nullable FlutterStandardTypedData *)frontSideDocumentImage
    backSideDocumentImage:(nullable FlutterStandardTypedData *)backSideDocumentImage
    signatureImage:(nullable FlutterStandardTypedData *)signatureImage
    classInfo:(nullable ClassInfo *)classInfo
    frontImageAnalysisResult:(nullable ImageAnalysisResult *)frontImageAnalysisResult
    backImageAnalysisResult:(nullable ImageAnalysisResult *)backImageAnalysisResult;
@property(nonatomic, strong, nullable) NSArray<ResultField *> * resultsFields;
@property(nonatomic, strong, nullable) FlutterStandardTypedData * faceImage;
@property(nonatomic, strong, nullable) FlutterStandardTypedData * frontSideDocumentImage;
@property(nonatomic, strong, nullable) FlutterStandardTypedData * backSideDocumentImage;
@property(nonatomic, strong, nullable) FlutterStandardTypedData * signatureImage;
@property(nonatomic, strong, nullable) ClassInfo * classInfo;
@property(nonatomic, strong, nullable) ImageAnalysisResult * frontImageAnalysisResult;
@property(nonatomic, strong, nullable) ImageAnalysisResult * backImageAnalysisResult;
@end

@interface IdvColor : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithColor:(NSString *)color
    darkModeColor:(nullable NSString *)darkModeColor;
@property(nonatomic, copy) NSString * color;
@property(nonatomic, copy, nullable) NSString * darkModeColor;
@end

@interface IdvFont : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSize:(NSNumber *)size
    weight:(nullable NSNumber *)weight;
@property(nonatomic, strong) NSNumber * size;
@property(nonatomic, strong, nullable) NSNumber * weight;
@end

@interface IdvFontFamily : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithName:(NSString *)name
    path:(NSString *)path;
@property(nonatomic, copy) NSString * name;
@property(nonatomic, copy) NSString * path;
@end

@interface IdvLocalizationTheme : NSObject
+ (instancetype)makeWithLocalizationFileName:(nullable NSString *)localizationFileName
    faceTecLocalizationFileName:(nullable NSString *)faceTecLocalizationFileName;
@property(nonatomic, copy, nullable) NSString * localizationFileName;
@property(nonatomic, copy, nullable) NSString * faceTecLocalizationFileName;
@end

@interface IdvColorTheme : NSObject
+ (instancetype)makeWithPrimaryColor:(nullable IdvColor *)primaryColor
    stepCaptionColor:(nullable IdvColor *)stepCaptionColor
    stepDisabledColor:(nullable IdvColor *)stepDisabledColor
    successColor:(nullable IdvColor *)successColor
    highlightColor:(nullable IdvColor *)highlightColor
    stepBackgroundSuccessColor:(nullable IdvColor *)stepBackgroundSuccessColor
    errorColor:(nullable IdvColor *)errorColor
    buttonBackgroundEnabledColor:(nullable IdvColor *)buttonBackgroundEnabledColor
    buttonBackgroundDisabledColor:(nullable IdvColor *)buttonBackgroundDisabledColor
    buttonTextDisabledColor:(nullable IdvColor *)buttonTextDisabledColor
    buttonTextEnabledColor:(nullable IdvColor *)buttonTextEnabledColor
    defaultBackgroundColor:(nullable IdvColor *)defaultBackgroundColor
    stepBackgroundColor:(nullable IdvColor *)stepBackgroundColor
    labelColor:(nullable IdvColor *)labelColor
    secondaryLabelColor:(nullable IdvColor *)secondaryLabelColor
    reviewDataEditBannerBackgroundColor:(nullable IdvColor *)reviewDataEditBannerBackgroundColor
    reviewDataEditBannerTextColor:(nullable IdvColor *)reviewDataEditBannerTextColor
    stepLabelColor:(nullable IdvColor *)stepLabelColor
    alertColor:(nullable IdvColor *)alertColor
    needsReviewColor:(nullable IdvColor *)needsReviewColor
    idInstructionsTextColor:(nullable IdvColor *)idInstructionsTextColor
    idFlashlightWarningBackgroundColor:(nullable IdvColor *)idFlashlightWarningBackgroundColor
    idFlashlightWarningTextColor:(nullable IdvColor *)idFlashlightWarningTextColor
    idReticleErrorColor:(nullable IdvColor *)idReticleErrorColor
    faceTecPrimaryColor:(nullable IdvColor *)faceTecPrimaryColor
    faceTecLoadingBarRailColor:(nullable IdvColor *)faceTecLoadingBarRailColor
    faceTecMainTextColor:(nullable IdvColor *)faceTecMainTextColor
    faceTecSubtextColor:(nullable IdvColor *)faceTecSubtextColor
    faceTecButtonTextColor:(nullable IdvColor *)faceTecButtonTextColor
    faceTecOvalColor:(nullable IdvColor *)faceTecOvalColor
    faceTecOvalProgressColor:(nullable IdvColor *)faceTecOvalProgressColor
    faceTecFeedbackBarBackgroundColor:(nullable IdvColor *)faceTecFeedbackBarBackgroundColor
    faceTecFeedbackBarTextColor:(nullable IdvColor *)faceTecFeedbackBarTextColor
    faceTecResultAnimationCheckmarkForegroundColor:(nullable IdvColor *)faceTecResultAnimationCheckmarkForegroundColor;
@property(nonatomic, strong, nullable) IdvColor * primaryColor;
@property(nonatomic, strong, nullable) IdvColor * stepCaptionColor;
@property(nonatomic, strong, nullable) IdvColor * stepDisabledColor;
@property(nonatomic, strong, nullable) IdvColor * successColor;
@property(nonatomic, strong, nullable) IdvColor * highlightColor;
@property(nonatomic, strong, nullable) IdvColor * stepBackgroundSuccessColor;
@property(nonatomic, strong, nullable) IdvColor * errorColor;
@property(nonatomic, strong, nullable) IdvColor * buttonBackgroundEnabledColor;
@property(nonatomic, strong, nullable) IdvColor * buttonBackgroundDisabledColor;
@property(nonatomic, strong, nullable) IdvColor * buttonTextDisabledColor;
@property(nonatomic, strong, nullable) IdvColor * buttonTextEnabledColor;
@property(nonatomic, strong, nullable) IdvColor * defaultBackgroundColor;
@property(nonatomic, strong, nullable) IdvColor * stepBackgroundColor;
@property(nonatomic, strong, nullable) IdvColor * labelColor;
@property(nonatomic, strong, nullable) IdvColor * secondaryLabelColor;
@property(nonatomic, strong, nullable) IdvColor * reviewDataEditBannerBackgroundColor;
@property(nonatomic, strong, nullable) IdvColor * reviewDataEditBannerTextColor;
@property(nonatomic, strong, nullable) IdvColor * stepLabelColor;
@property(nonatomic, strong, nullable) IdvColor * alertColor;
@property(nonatomic, strong, nullable) IdvColor * needsReviewColor;
@property(nonatomic, strong, nullable) IdvColor * idInstructionsTextColor;
@property(nonatomic, strong, nullable) IdvColor * idFlashlightWarningBackgroundColor;
@property(nonatomic, strong, nullable) IdvColor * idFlashlightWarningTextColor;
@property(nonatomic, strong, nullable) IdvColor * idReticleErrorColor;
@property(nonatomic, strong, nullable) IdvColor * faceTecPrimaryColor;
@property(nonatomic, strong, nullable) IdvColor * faceTecLoadingBarRailColor;
@property(nonatomic, strong, nullable) IdvColor * faceTecMainTextColor;
@property(nonatomic, strong, nullable) IdvColor * faceTecSubtextColor;
@property(nonatomic, strong, nullable) IdvColor * faceTecButtonTextColor;
@property(nonatomic, strong, nullable) IdvColor * faceTecOvalColor;
@property(nonatomic, strong, nullable) IdvColor * faceTecOvalProgressColor;
@property(nonatomic, strong, nullable) IdvColor * faceTecFeedbackBarBackgroundColor;
@property(nonatomic, strong, nullable) IdvColor * faceTecFeedbackBarTextColor;
@property(nonatomic, strong, nullable) IdvColor * faceTecResultAnimationCheckmarkForegroundColor;
@end

@interface IdvFontTheme : NSObject
+ (instancetype)makeWithNavigationBarTitleFont:(nullable IdvFont *)navigationBarTitleFont
    buttonFont:(nullable IdvFont *)buttonFont
    dataCaptionFont:(nullable IdvFont *)dataCaptionFont
    dataTitleFont:(nullable IdvFont *)dataTitleFont
    dataHeaderFont:(nullable IdvFont *)dataHeaderFont
    titleFont:(nullable IdvFont *)titleFont
    buttonStartFont:(nullable IdvFont *)buttonStartFont
    stepTitleFont:(nullable IdvFont *)stepTitleFont
    stepNumberFont:(nullable IdvFont *)stepNumberFont
    secondaryLabelFont:(nullable IdvFont *)secondaryLabelFont
    faceTecMessageFont:(nullable IdvFont *)faceTecMessageFont
    faceTecHeaderFont:(nullable IdvFont *)faceTecHeaderFont
    faceTecSubtextFont:(nullable IdvFont *)faceTecSubtextFont
    faceTecButtonFont:(nullable IdvFont *)faceTecButtonFont
    idInstructionsFont:(nullable IdvFont *)idInstructionsFont
    idFlashlightWarningFont:(nullable IdvFont *)idFlashlightWarningFont
    fontFamily:(nullable IdvFontFamily *)fontFamily;
@property(nonatomic, strong, nullable) IdvFont * navigationBarTitleFont;
@property(nonatomic, strong, nullable) IdvFont * buttonFont;
@property(nonatomic, strong, nullable) IdvFont * dataCaptionFont;
@property(nonatomic, strong, nullable) IdvFont * dataTitleFont;
@property(nonatomic, strong, nullable) IdvFont * dataHeaderFont;
@property(nonatomic, strong, nullable) IdvFont * titleFont;
@property(nonatomic, strong, nullable) IdvFont * buttonStartFont;
@property(nonatomic, strong, nullable) IdvFont * stepTitleFont;
@property(nonatomic, strong, nullable) IdvFont * stepNumberFont;
@property(nonatomic, strong, nullable) IdvFont * secondaryLabelFont;
@property(nonatomic, strong, nullable) IdvFont * faceTecMessageFont;
@property(nonatomic, strong, nullable) IdvFont * faceTecHeaderFont;
@property(nonatomic, strong, nullable) IdvFont * faceTecSubtextFont;
@property(nonatomic, strong, nullable) IdvFont * faceTecButtonFont;
@property(nonatomic, strong, nullable) IdvFont * idInstructionsFont;
@property(nonatomic, strong, nullable) IdvFont * idFlashlightWarningFont;
@property(nonatomic, strong, nullable) IdvFontFamily * fontFamily;
@end

@interface IdvImageTheme : NSObject
+ (instancetype)makeWithLandingIllustration:(nullable NSString *)landingIllustration
    iconCheckmarkLarge:(nullable NSString *)iconCheckmarkLarge
    iconCrossLarge:(nullable NSString *)iconCrossLarge
    iconCompleteVerificationBackground:(nullable NSString *)iconCompleteVerificationBackground
    iconActionCheckmark:(nullable NSString *)iconActionCheckmark
    iconLock:(nullable NSString *)iconLock
    iconEditField:(nullable NSString *)iconEditField
    editResultsHeaderIcon:(nullable NSString *)editResultsHeaderIcon
    loadingIndicator:(nullable NSString *)loadingIndicator
    idSuccessScanningImage:(nullable NSString *)idSuccessScanningImage
    idFrontCardImage:(nullable NSString *)idFrontCardImage
    idBackCardImage:(nullable NSString *)idBackCardImage
    faceTecCameraPermission:(nullable NSString *)faceTecCameraPermission
    faceTecIdealSelfie:(nullable NSString *)faceTecIdealSelfie
    faceTecProgressSelfieDoneBackground:(nullable NSString *)faceTecProgressSelfieDoneBackground
    faceTecIconClose:(nullable NSString *)faceTecIconClose;
@property(nonatomic, copy, nullable) NSString * landingIllustration;
@property(nonatomic, copy, nullable) NSString * iconCheckmarkLarge;
@property(nonatomic, copy, nullable) NSString * iconCrossLarge;
@property(nonatomic, copy, nullable) NSString * iconCompleteVerificationBackground;
@property(nonatomic, copy, nullable) NSString * iconActionCheckmark;
@property(nonatomic, copy, nullable) NSString * iconLock;
@property(nonatomic, copy, nullable) NSString * iconEditField;
@property(nonatomic, copy, nullable) NSString * editResultsHeaderIcon;
@property(nonatomic, copy, nullable) NSString * loadingIndicator;
@property(nonatomic, copy, nullable) NSString * idSuccessScanningImage;
@property(nonatomic, copy, nullable) NSString * idFrontCardImage;
@property(nonatomic, copy, nullable) NSString * idBackCardImage;
@property(nonatomic, copy, nullable) NSString * faceTecCameraPermission;
@property(nonatomic, copy, nullable) NSString * faceTecIdealSelfie;
@property(nonatomic, copy, nullable) NSString * faceTecProgressSelfieDoneBackground;
@property(nonatomic, copy, nullable) NSString * faceTecIconClose;
@end

@interface IdvSize : NSObject
+ (instancetype)makeWithWidth:(nullable NSNumber *)width
    height:(nullable NSNumber *)height;
@property(nonatomic, strong, nullable) NSNumber * width;
@property(nonatomic, strong, nullable) NSNumber * height;
@end

@interface IdvViewTheme : NSObject
+ (instancetype)makeWithFaceImageCornerRadius:(nullable NSNumber *)faceImageCornerRadius
    buttonCornerRadius:(nullable NSNumber *)buttonCornerRadius
    actionViewCornerRadius:(nullable NSNumber *)actionViewCornerRadius
    actionStepCornerRadius:(nullable NSNumber *)actionStepCornerRadius
    resultsPersonImageCornerRadius:(nullable NSNumber *)resultsPersonImageCornerRadius
    stepViewShadowColor:(nullable NSString *)stepViewShadowColor
    stepViewShadowOffset:(nullable IdvSize *)stepViewShadowOffset
    stepViewShadowOpacity:(nullable NSNumber *)stepViewShadowOpacity
    stepViewShadowRadius:(nullable NSNumber *)stepViewShadowRadius
    buttonHeight:(nullable NSNumber *)buttonHeight
    idInstructionsCornerRadius:(nullable NSNumber *)idInstructionsCornerRadius
    idFlashlightWarningCornerRadius:(nullable NSNumber *)idFlashlightWarningCornerRadius;
@property(nonatomic, strong, nullable) NSNumber * faceImageCornerRadius;
@property(nonatomic, strong, nullable) NSNumber * buttonCornerRadius;
@property(nonatomic, strong, nullable) NSNumber * actionViewCornerRadius;
@property(nonatomic, strong, nullable) NSNumber * actionStepCornerRadius;
@property(nonatomic, strong, nullable) NSNumber * resultsPersonImageCornerRadius;
@property(nonatomic, copy, nullable) NSString * stepViewShadowColor;
@property(nonatomic, strong, nullable) IdvSize * stepViewShadowOffset;
@property(nonatomic, strong, nullable) NSNumber * stepViewShadowOpacity;
@property(nonatomic, strong, nullable) NSNumber * stepViewShadowRadius;
@property(nonatomic, strong, nullable) NSNumber * buttonHeight;
@property(nonatomic, strong, nullable) NSNumber * idInstructionsCornerRadius;
@property(nonatomic, strong, nullable) NSNumber * idFlashlightWarningCornerRadius;
@end

@interface IdvNavigationTheme : NSObject
+ (instancetype)makeWithBarStyle:(BarStyle)barStyle
    isTranslucent:(nullable NSNumber *)isTranslucent
    hideBarButtonOnSuccessfulVerification:(nullable NSNumber *)hideBarButtonOnSuccessfulVerification
    barTintColor:(nullable NSString *)barTintColor
    titleColor:(nullable NSString *)titleColor
    barButtonItemColor:(nullable NSString *)barButtonItemColor;
@property(nonatomic, assign) BarStyle barStyle;
@property(nonatomic, strong, nullable) NSNumber * isTranslucent;
@property(nonatomic, strong, nullable) NSNumber * hideBarButtonOnSuccessfulVerification;
@property(nonatomic, copy, nullable) NSString * barTintColor;
@property(nonatomic, copy, nullable) NSString * titleColor;
@property(nonatomic, copy, nullable) NSString * barButtonItemColor;
@end

@interface IdvDateFormatterTheme : NSObject
+ (instancetype)makeWithCustomDateFormat:(nullable NSString *)customDateFormat;
@property(nonatomic, copy, nullable) NSString * customDateFormat;
@end

/// The codec used by IdvPlatformApi.
NSObject<FlutterMessageCodec> *IdvPlatformApiGetCodec(void);

@protocol IdvPlatformApi
- (void)startVerificationIdvConfiguration:(IdvConfiguration *)idvConfiguration completion:(void(^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)setupIdentityVerificationCustomizationColorTheme:(nullable IdvColorTheme *)colorTheme fontTheme:(nullable IdvFontTheme *)fontTheme imageTheme:(nullable IdvImageTheme *)imageTheme localizationTheme:(nullable IdvLocalizationTheme *)localizationTheme viewTheme:(nullable IdvViewTheme *)viewTheme navigationTheme:(nullable IdvNavigationTheme *)navigationTheme dateFormatterTheme:(nullable IdvDateFormatterTheme *)dateFormatterTheme completion:(void(^)(FlutterError *_Nullable))completion;
@end

extern void IdvPlatformApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<IdvPlatformApi> *_Nullable api);

/// The codec used by IdvDartApi.
NSObject<FlutterMessageCodec> *IdvDartApiGetCodec(void);

@interface IdvDartApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onLivenessCheckSuccessImage:(nullable FlutterStandardTypedData *)image completion:(void(^)(NSError *_Nullable))completion;
- (void)onVerificationResultVerificationResult:(VerificationResult *)verificationResult completion:(void(^)(NSError *_Nullable))completion;
- (void)onResultConfirmedDocumentResult:(DocumentResult *)documentResult completion:(void(^)(NSError *_Nullable))completion;
- (void)onLivenessCheckFailureFeebackCode:(NSString *)feebackCode completion:(void(^)(NSError *_Nullable))completion;
- (void)onLivenessCheckErrorError:(nullable NSString *)error completion:(void(^)(NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
